package SISTEMA_VENTAS;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import GESTION_CLIENTES.Gestion_clientes;
import GESTION_PROVEEDORES.Gestion_proveedores;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAYMUNDO
 */
public class Software extends javax.swing.JFrame {

    Usuarios usuarios = new Usuarios();
    Productos producto = new Productos();
    Ventas venta = new Ventas();
    
    DefaultTableModel dm;
    
    

    public Software() {
        initComponents();
        usuarios.CabeceraUsuario(jTableUsuarios);
        producto.CebeceraProductos(jTableProducto);
        venta.CebecerasubTotalVenta(jTableSubtotal);
        
        
        createColumns();
    }
    
    private void createColumns()
    {
        dm = (DefaultTableModel)jTableProducto.getModel();
 
    }
    
    //Add Rows
    private void Populate (String name, String pos, String team)
    {
        //Get model
         dm = (DefaultTableModel)jTableProducto.getModel();
    
         //Get rows;
         
         String []rowData ={name,pos,team};
         
         
         dm.addRow(rowData);
         
         
    }
    
    
    
    
    
    
    

    //Metodo para desactivar los txt's
    public void DisableTextBoxes() {
        txtnombres.setEnabled(false);
        txtapellidos.setEnabled(false);
        txtdni.setEnabled(false);
        txtcelular.setEnabled(false);
        txtcorreo.setEnabled(false);
        btnagregarusuarios.setEnabled(false);
        jTableUsuarios.setEnabled(false);
        btneliminaru.setEnabled(false);

        //AGRENDO INFO DEL USUARIO:
        lblRol.setText("Cajero001");

    }

    //Metodo para desactivar los txt's
    public void LoginAdministrador() {

        //AGRENDO INFO DEL USUARIO:
        lblRol.setText("Administrador");

    }

    public void close() {

        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public String[] datos(String datos) {
        String[] informacion = new String[1];
        
            if (datos.equalsIgnoreCase("Tinas")) {
                informacion[0] = "20";

            } else if (datos.equalsIgnoreCase("Jarras")) {
                informacion[0] = "21";
            } else if (datos.equalsIgnoreCase("Vasos")) {
                informacion[0] = "22";

            } else if (datos.equalsIgnoreCase("Escobas")) {
                informacion[0] = "23";
            } else if (datos.equalsIgnoreCase("Jarrones")) {
                informacion[0] = "24";

            } else if (datos.equalsIgnoreCase("Platos")) {
                informacion[0] = "25";
            } else if (datos.equalsIgnoreCase("Cucharas")) {
                informacion[0] = "26";

            } else if (datos.equalsIgnoreCase("Sillas")) {
                informacion[0] = "27";
            } else if (datos.equalsIgnoreCase("Mesas")) {
                informacion[0] = "28";
            }
            return informacion;
        }
    
    
    public String[] precio(String precio) {
        String[] informacion = new String[1];
        
            if (precio.equalsIgnoreCase("Tinas")) {
                informacion[0] = "28";

            } else if (precio.equalsIgnoreCase("Jarras")) {
                informacion[0] = "27";
            } else if (precio.equalsIgnoreCase("Vasos")) {
                informacion[0] = "26";

            } else if (precio.equalsIgnoreCase("Escobas")) {
                informacion[0] = "25";
            } else if (precio.equalsIgnoreCase("Jarrones")) {
                informacion[0] = "24";

            } else if (precio.equalsIgnoreCase("Platos")) {
                informacion[0] = "23";
            } else if (precio.equalsIgnoreCase("Cucharas")) {
                informacion[0] = "22";

            } else if (precio.equalsIgnoreCase("Sillas")) {
                informacion[0] = "21";
            } else if (precio.equalsIgnoreCase("Mesas")) {
                informacion[0] = "20";
            }
            return informacion;
        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnagregarusuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        btneliminaru = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtagregarp = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cmbdescripcion = new javax.swing.JComboBox<>();
        cmbstock = new javax.swing.JComboBox<>();
        cmbprecio = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btncomprar = new javax.swing.JButton();
        txteliminarp = new javax.swing.JButton();
        txtcant = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSubtotal = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txteliminars = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnExportarSubTotal = new javax.swing.JButton();
        btnExportarCantidad = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        btnGestionarClientes = new javax.swing.JButton();
        btnGestionarProvee = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(102, 0, 153));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("NOMBRES:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 153));
        jLabel3.setText("APELLIDOS:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setText("DNI:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 153));
        jLabel5.setText("CELULAR:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 153));
        jLabel6.setText("CORREO:");

        txtnombres.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtnombres.setForeground(new java.awt.Color(153, 0, 204));
        txtnombres.setCaretColor(new java.awt.Color(102, 0, 204));
        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        txtapellidos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtapellidos.setForeground(new java.awt.Color(153, 0, 204));
        txtapellidos.setCaretColor(new java.awt.Color(102, 0, 204));
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        txtdni.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtdni.setForeground(new java.awt.Color(153, 0, 204));
        txtdni.setCaretColor(new java.awt.Color(102, 0, 204));
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniKeyTyped(evt);
            }
        });

        txtcelular.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtcelular.setForeground(new java.awt.Color(153, 0, 204));
        txtcelular.setCaretColor(new java.awt.Color(102, 0, 204));
        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularKeyTyped(evt);
            }
        });

        txtcorreo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(153, 0, 204));
        txtcorreo.setCaretColor(new java.awt.Color(102, 0, 204));
        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreoFocusLost(evt);
            }
        });
        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SISTEMA_VENTAS/Imagenes/icons8-contact-details-64.png"))); // NOI18N
        jLabel7.setText("USUARIO");

        btnagregarusuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnagregarusuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnagregarusuarios.setForeground(new java.awt.Color(153, 0, 204));
        btnagregarusuarios.setText("AGREGAR");
        btnagregarusuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnagregarusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarusuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnagregarusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(txtcorreo)
                    .addComponent(txtnombres)
                    .addComponent(txtapellidos)
                    .addComponent(txtdni)
                    .addComponent(txtcelular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnagregarusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(224, 224, 224));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SISTEMA_VENTAS/Imagenes/icons8-buy-for-change-64.png"))); // NOI18N
        jLabel1.setText("SISTEMA DE VENTA");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableUsuarios.setBackground(new java.awt.Color(224, 224, 224));
        jTableUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableUsuarios.setForeground(new java.awt.Color(153, 0, 204));
        jScrollPane1.setViewportView(jTableUsuarios);

        btneliminaru.setBackground(new java.awt.Color(255, 255, 255));
        btneliminaru.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneliminaru.setForeground(new java.awt.Color(153, 0, 204));
        btneliminaru.setText("ELIMINAR");
        btneliminaru.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminaruActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SISTEMA_VENTAS/Imagenes/icons8-add-shopping-cart-64.png"))); // NOI18N
        jLabel8.setText("PRODUCTO");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 153));
        jLabel9.setText("DESCRIPCION");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 153));
        jLabel10.setText("STOCK");

        txtagregarp.setBackground(new java.awt.Color(255, 255, 255));
        txtagregarp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtagregarp.setForeground(new java.awt.Color(153, 0, 204));
        txtagregarp.setText("AGREGAR");
        txtagregarp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtagregarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagregarpActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 153));
        jLabel17.setText("PRECIO");

        cmbdescripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Seleccionar", "Tinas", "Jarras", "Vasos", "Escobas", "Jarrones", "Platos", "Cucharas", "Sillas", "Mesas" }));
        cmbdescripcion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbdescripcionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cmbdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cmbstock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbprecio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(txtagregarp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtagregarp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jTableProducto.setBackground(new java.awt.Color(224, 224, 224));
        jTableProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableProducto.setForeground(new java.awt.Color(153, 0, 204));
        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableProducto);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 153));
        jLabel12.setText("CANTIDAD A COMPRAR");

        btncomprar.setBackground(new java.awt.Color(255, 255, 255));
        btncomprar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncomprar.setForeground(new java.awt.Color(153, 0, 204));
        btncomprar.setText("COMPRAR");
        btncomprar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });

        txteliminarp.setBackground(new java.awt.Color(255, 255, 255));
        txteliminarp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txteliminarp.setForeground(new java.awt.Color(153, 0, 204));
        txteliminarp.setText("ELIMINAR");
        txteliminarp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txteliminarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteliminarpActionPerformed(evt);
            }
        });

        txtcant.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtcant.setForeground(new java.awt.Color(153, 0, 204));
        txtcant.setCaretColor(new java.awt.Color(102, 0, 204));
        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });

        jTableSubtotal.setBackground(new java.awt.Color(224, 224, 224));
        jTableSubtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableSubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableSubtotal.setForeground(new java.awt.Color(153, 0, 204));
        jTableSubtotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableSubtotal.setAlignmentX(1.0F);
        jTableSubtotal.setAlignmentY(1.0F);
        jScrollPane3.setViewportView(jTableSubtotal);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 204));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SISTEMA_VENTAS/Imagenes/icons8-paycheque-64.png"))); // NOI18N
        jLabel13.setText("SUBTOTAL");

        txteliminars.setBackground(new java.awt.Color(255, 255, 255));
        txteliminars.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txteliminars.setForeground(new java.awt.Color(153, 0, 204));
        txteliminars.setText("ELIMINAR");
        txteliminars.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txteliminars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteliminarsActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 204));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SISTEMA_VENTAS/Imagenes/icons8-cheap-64.png"))); // NOI18N
        jLabel14.setText("FACTURA TOTAL  S/.");

        txttotal.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txttotal.setForeground(new java.awt.Color(153, 0, 204));
        txttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnExportarSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        btnExportarSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExportarSubTotal.setForeground(new java.awt.Color(153, 0, 204));
        btnExportarSubTotal.setText("EXPORTAR SUB-TOTAL");
        btnExportarSubTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExportarSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarSubTotalActionPerformed(evt);
            }
        });

        btnExportarCantidad.setBackground(new java.awt.Color(255, 255, 255));
        btnExportarCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExportarCantidad.setForeground(new java.awt.Color(153, 0, 204));
        btnExportarCantidad.setText("EXPORTAR CANTIDAD");
        btnExportarCantidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExportarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarCantidadActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Bienvenido :");

        lblRol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRol.setText("Texto");

        btnGestionarClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarClientes.setForeground(new java.awt.Color(153, 0, 204));
        btnGestionarClientes.setText("GESTIONAR CLIENTES");
        btnGestionarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarClientesActionPerformed(evt);
            }
        });

        btnGestionarProvee.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarProvee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarProvee.setForeground(new java.awt.Color(153, 0, 204));
        btnGestionarProvee.setText("GESTONAR PROVEEDORES");
        btnGestionarProvee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestionarProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProveeActionPerformed(evt);
            }
        });

        btnExportar.setBackground(new java.awt.Color(255, 255, 255));
        btnExportar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(153, 0, 204));
        btnExportar.setText("Exportar");
        btnExportar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btneliminaru, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(btncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txteliminarp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(btnExportarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel13)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(txteliminars, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnExportarSubTotal)
                                            .addGap(253, 253, 253)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(btnGestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGestionarProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(jLabel15)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txteliminarp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExportarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btneliminaru, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txteliminars, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportarSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblRol)
                    .addComponent(btnGestionarProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed
        // TODO add your haning code here:
    }//GEN-LAST:event_txtnombresActionPerformed

    private void btneliminaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminaruActionPerformed
        usuarios.eliminarfilaUsuario(jTableUsuarios);
    }//GEN-LAST:event_btneliminaruActionPerformed

    private void txtagregarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagregarpActionPerformed
        /*producto.AgregarProducto(txtdescripcion, txtstock, txtprecio);
        producto.LimpiarDatosProductos(txtdescripcion, txtstock, txtprecio);*/
        
        Populate(cmbdescripcion.getSelectedItem().toString(), cmbstock.getSelectedItem().toString(), cmbprecio.getSelectedItem().toString());
       
        
    }//GEN-LAST:event_txtagregarpActionPerformed

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        venta.AgregarTablaVentas(txtcant, jTableProducto, jTableSubtotal, txttotal);

    }//GEN-LAST:event_btncomprarActionPerformed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantActionPerformed

    private void btnagregarusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarusuariosActionPerformed
        usuarios.AgregarUsuario(txtnombres, txtapellidos, txtdni, txtcelular, txtcorreo);
        usuarios.LimpiarDatosUsuario(txtnombres, txtapellidos, txtdni, txtcelular, txtcorreo);
    }//GEN-LAST:event_btnagregarusuariosActionPerformed

    private void txteliminarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteliminarsActionPerformed

        venta.eliminarfilaventa(jTableSubtotal, txttotal);
    }//GEN-LAST:event_txteliminarsActionPerformed

    private void txteliminarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteliminarpActionPerformed
        producto.eliminarfilaProducto(jTableProducto);
    }//GEN-LAST:event_txteliminarpActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnExportarSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarSubTotalActionPerformed
        if (jTableSubtotal.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List tb = new ArrayList();
                List nom = new ArrayList();
                tb.add(jTableSubtotal);
                nom.add("Compras por factura");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos para exportar", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportarSubTotalActionPerformed

    private void btnExportarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCantidadActionPerformed
        if (jTableProducto.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List tb = new ArrayList();
                List nom = new ArrayList();
                tb.add(jTableProducto);
                nom.add("Compras por factura");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos para exportar", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportarCantidadActionPerformed

    private void btnGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClientesActionPerformed

        Gestion_clientes gestion_clientes = new Gestion_clientes();

        gestion_clientes.setVisible(true);

        close();


    }//GEN-LAST:event_btnGestionarClientesActionPerformed

    private void btnGestionarProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProveeActionPerformed

        GESTION_PROVEEDORES.Gestion_proveedores gestion_proveedores = new Gestion_proveedores();
        gestion_proveedores.setVisible(true);

        close();
    }//GEN-LAST:event_btnGestionarProveeActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        if (jTableSubtotal.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List tb = new ArrayList();
                List nom = new ArrayList();
                tb.add(jTableSubtotal);
                nom.add("Compras por factura");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos para exportar", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnExportarActionPerformed

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        // TODO add your handling code here:
        char nombres = evt.getKeyChar();
        if ((nombres < 'a' || nombres > 'z') && (nombres < 'A' || nombres > 'Z')
                && (nombres != (char) KeyEvent.VK_BACK_SPACE) && (nombres != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "! Solo se admite texto !", "VALIDANDO NOMBRES",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        // TODO add your handling code here:
        char nombres = evt.getKeyChar();
        if ((nombres < 'a' || nombres > 'z') && (nombres < 'A' || nombres > 'Z')
                && (nombres != (char) KeyEvent.VK_BACK_SPACE) && (nombres != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "¡ Solo se admite texto !", "VALIDANDO APELLIDOS",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txtdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyTyped
        // TODO add your handling code here:
        char dni = evt.getKeyChar();
        if (txtdni.getText().length() == 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Solo se admiten 8 digitos");

        }
        if ((dni < '0' || dni > '9') && (dni != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "¡ Solo se admiten números !", "VALIDANDO DNI",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if ((dni < '0' || dni > '9') && (dni != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "¡ Solo se admiten números !", "VALIDANDO DNI",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtdniKeyTyped

    private void txtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyTyped
        // TODO add your handling code here:
        char celular = evt.getKeyChar();
        if (txtcelular.getText().length() == 9) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Solo se admiten 9 digitos");
        }
        if ((celular < '0' || celular > '9') && (celular != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "¡ Solo se admiten números !", "VALIDANDO CELULAR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if ((celular < '0' || celular > '9') && (celular != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "¡ Solo se admiten números !", "VALIDANDO CELULAR",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtcelularKeyTyped

    public boolean isEmail(String correo) {
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("@.");
        mat = pat.matcher(correo);
        if (mat.find()) {
            return true;
        } else {
            return false;
        }

    }

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_txtcorreoKeyTyped

    private void txtcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusLost
        // TODO add your handling code here:
        if (isEmail(txtcorreo.getText())) {
        } else {
            JOptionPane.showMessageDialog(null, "Correo incorrecto", "VALIDANDO CORREO",
                    JOptionPane.INFORMATION_MESSAGE);
            txtcorreo.requestFocus();
        }

    }//GEN-LAST:event_txtcorreoFocusLost

    private void cmbdescripcionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbdescripcionItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.cmbdescripcion.getSelectedIndex() > 0) {
                this.cmbstock.setModel(new DefaultComboBoxModel(this.datos(this.cmbdescripcion.getSelectedItem().toString())));
            }
        }
        
         if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.cmbdescripcion.getSelectedIndex() > 0) {
                this.cmbprecio.setModel(new DefaultComboBoxModel(this.precio(this.cmbdescripcion.getSelectedItem().toString())));
            }
        }

    }//GEN-LAST:event_cmbdescripcionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Software.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Software.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Software.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Software.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Software().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnExportarCantidad;
    private javax.swing.JButton btnExportarSubTotal;
    private javax.swing.JButton btnGestionarClientes;
    private javax.swing.JButton btnGestionarProvee;
    private javax.swing.JButton btnagregarusuarios;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btneliminaru;
    private javax.swing.JComboBox<String> cmbdescripcion;
    private javax.swing.JComboBox<String> cmbprecio;
    private javax.swing.JComboBox<String> cmbstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTable jTableSubtotal;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JLabel lblRol;
    private javax.swing.JButton txtagregarp;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JButton txteliminarp;
    private javax.swing.JButton txteliminars;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
